
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build-angular-debug:
    
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: npm install and build
        run: |
          npm install
          npm run build
    build-angular-prod:
    
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: npm install and build
        run: |
          npm install
          npm run build --prod
